### ISSUE TITLE
[feature] Dependency injection in custom Producer

### ISSUE THREAD

**Issue by FredoVelcro-zz** [php-amqplib/RabbitMqBundle#202]
Hello,

I need to inject a service in my custom Producer class (extends OldSound\RabbitMqBundle\RabbitMq\Producer like explained in the doc)

As a Producer is built by the OldSoundRabbitMqExtension, how can i do this ?

Thank ;)

**Comment by Plasmagun86** [comment]
Hello,

I need this too, did you make any progress on this subject ?

Thanks

**Comment by kolinko-ant** [comment]
I need this as well. Guys, did you find any solution to do that?

**Comment by skafandri** [comment]
is the use case about ALL producers or for some particular ones?

**Comment by Plasmagun86** [comment]
In my case, we add a parameter in headers on all RabbitMq message that define a client_token.
This token is found in the request in the route.

**Comment by nacmartin** [comment]
You can always create a service MyProducerWrapper, inject the producer in its constructor along with whatever other services you need and use it instead of the producer service that this bundle creates. Not ideal, but works, and depending on the case it may be cleaner to have a wrapper that exposes the api you want than using directly the producer.
