### ISSUE TITLE
Discussion: Setup fabric and deprecation of bindings and queues

### ISSUE THREAD

**Issue by AntonStoeckl** [php-amqplib/RabbitMqBundle#355]
Hi folks!
I'd like to get some opinions on that before I consider to start a PR.

We're using the setup fabric command to declare everything in our deployments (via Jenkins). This works find to declare "new" things, but currently there is no possibility to "deprecate" bindings or queues, so if our domain code changes we need to clean up old stuff manually.

That's why we think it would be great to be handle this via setup fabric, for example by declaring stuff as deprecated in config.

Natur of deprecated queues and deprecated bindings is different. Also it depends on how Rabbit is used for sure. We're doing pub-sub with topic.

If we have a deprecated binding it should be removed immediately when we deploy, to not receive messages that we don't want to consume. We prefer to throw exceptions here (unexpected ...) instead of just slilently ignoring them.

Deprecated queues don't hurt immediately, there will be no consumer any more, so the only issue will be queues that fill up. In high throughput applications this can be a problem for sure.

So how about this:
- add options in config to deprecate queues and bindings
- setup fabric unbinds / deletes (what if the queue is not empty?)

Would that work for folks that do stuff totally different than we do it? Hard for me to abstract how other projects use Rabbit.

**Comment by skafandri** [comment]
This is an interesting issue. I can think about 2 ways to achieve it:
**Option1**: setup fabric cleans everything that is not in the config (a diff between the actual rabbit server and the current configuration)
**Option2**: explicitly set deprecated stuff

Option1 can be tricky when using wildcard bindings, it can be also risky when rabbit is shared between more than one application (I know is not a good usage, but many teams I worked with use this pattern)
Option2 is preferable from my point of view because it gives me more control. The concern is when the command is used as a part of a release script.
Many teams I worked with are using [canary](http://martinfowler.com/bliki/CanaryRelease.html) or [blue/green](http://martinfowler.com/bliki/BlueGreenDeployment.html) release or a variant of those, in other words, **old** and **new** queues/bindings/consumers.. coexist for some time (seconds, minutes, even hours..). Adding new queues/bindings.. should happen right before activating the new code. When can we delete deprecated stuff?

In all the cases, activating such a feature should be explicit, something like `$ ./app/console rabbitmq:setup-fabric --clean`

**Comment by AntonStoeckl** [comment]
Good input you mentioned on option 2, I agree this needs to be considered.

Totally agree with explicity!

It seems everything is depending on a) application and b) deployment.
Typically there will be N > 1 servers that run consumers, but only one RabbitMQ cluster.

How about this:
Use a different command for purging / unbinding old stuff (or a switch like --clean only does teardown).
This gives the possibility to either run setup and teardown both before or after code is deployed, or run setup, then deploy code, then run teardown.

**Comment by skafandri** [comment]
I think a different command is a good idea. What about?
````
rabbitmq:purge-fabric
rabbitmq:clean-fabric
````
I would also have the command run in interactive mode by default, unless a `--force` option is provided. A `--dry-run` option would also be helpful.
For everyone who wants to help with code/documentation I created a **purge-fabric** branch.
