### ISSUE TITLE
Misleading example or advice

### ISSUE THREAD

**Issue by BentCoder** [php-amqplib/RabbitMqBundle#356]
Hi,

In [Usage](https://github.com/php-amqplib/RabbitMqBundle#usage) section, `read_write_timeout: 3` and `heartbeat: 0` however, in [Heartbeat](https://github.com/php-amqplib/RabbitMqBundle#import-notice---heartbeats) section we see this message:

> It's a good idea to set the `read_write_timeout` to **2x** the `heartbeat` so your socket will be open. If you don't do this, or use a different multiplier, there's a risk the consumer socket will timeout.

So the question is, which one is right or wrong? To me if the `heartbeat` is **0** then the `read_write_timeout` should be **0** as well because `0X0=0`. Where does **3** come from? Is it just a typo?

Also, is this a correct example or what is the most reasonable value for each?
```
read_write_timeout: 120
heartbeat: 60
```

Thanks

**Comment by skafandri** [comment]
The values in [Usage](https://github.com/php-amqplib/RabbitMqBundle#usage) are just to show possible configurations and are by no mean recommendations.

Setting read_write_timeout to 2x the heartbeat is a good idea in most of the cases but not all.

For very busy consumers, set hearbeat to 0. Just saves bandwidth and broker extra work.

Is really hard to determine a good value for `read_write_timeout` as it depends on your application and architecture.
In one application, we have a process that launches consumers proportionally to the number of ready messages. We configure those consumers with `read_write_timeout: 60`. So when we dispatch more consumers in response to a spike, the scale down happens within maximum 60 seconds if there is no more traffic on that queue.
In another application, we have a heavy loading consumer (+10s, warms up it's cache...) in this case, we configure those consumers with `read_write_timeout: 3600`. In practice those consumers restarts only when updated.

A heartbeat bigger than the smallest timeout of any network device between the client and the broker is almost useless.

**Comment by BentCoder** [comment]
@skafandri Thank you very much with the much detailed answer. Much appreciated.

This is the final question which will help me to understand it even more. Personally, what would you set `read_write_timeout ` and `heartbeat ` to for the cases below?

CASE 1:
1 consumer handles 60 messages per minute.
```
read_write_timeout: ?
heartbeat: ?
```

CASE 2:
1 consumer handles 600 messages per minute.
```
read_write_timeout: ?
heartbeat: ?
```

**Comment by skafandri** [comment]
It is better to think about it as how long your consumer spends processing a message rather than how many messages per minute.
60 messages / minute => 1 second per message => your read_write_timeout must be greater than 1 second in this case.
Basically, it will prevent your consumer from getting disconnected while processing a message.

The second factor is: How long your consumer can be idle (no messages to process) and how expensive it is for it to either restart or to reconnect. So if your consumer _can_ process 60 messages per minute but your queue may be empty during let's say 30 seconds, it will get disconnected. Here comes the heartbeat that will _protect_ your consumer from disconnecting.

@BentCoder I will try to write a long version explanation about those concepts (and others) in the main documentation so everybody can benefit from it. https://github.com/php-amqplib/RabbitMqBundle/issues/364

**Comment by BentCoder** [comment]
@skafandri It just goes to show that the second factor has just exposed my misunderstand of "idle" logic. I thought that the consumer, connection etc. would always remain active or be ready to process next job even in the case of inactivity for hours :) Obviously I got it wrong.

Anyway, I'll keep an eye on your update on the documentation. Thanks
